### PR TITLE
SSE UTF32 =>  latin1

### PR DESCRIPTION
**Pull request by Nick-Nuon**
These are the benchmarks on big1/ gcc 11.3.1:

```

   
    convert_utf32_to_latin1+haswell, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   0.180 ins/byte,    0.136 cycle/byte,   23.542 GB/s (1.1 %),     3.197 GHz,    1.325 ins/cycle 
   0.719 ins/char,    0.543 cycle/char,    5.886 Gc/s (1.1 %)     4.00 byte/char 
convert_utf32_to_latin1+icelake, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   0.172 ins/byte,    0.130 cycle/byte,   23.737 GB/s (0.9 %),     3.097 GHz,    1.319 ins/cycle 
   0.688 ins/char,    0.522 cycle/char,    5.934 Gc/s (0.9 %)     4.00 byte/char 
convert_utf32_to_latin1+iconv, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
  10.006 ins/byte,    1.785 cycle/byte,    1.785 GB/s (18.5 %),     3.186 GHz,    5.606 ins/cycle 
  40.023 ins/char,    7.139 cycle/char,    0.446 Gc/s (18.5 %)     4.00 byte/char 
WARNING: Measurements are noisy, try increasing iteration count (-I).
convert_utf32_to_latin1+icu, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
/home/leorio/simdutf/build/benchmarks/benchmark
  19.687 ins/byte,    3.691 cycle/byte,    0.864 GB/s (3.6 %),     3.188 GHz,    5.334 ins/cycle 
  78.748 ins/char,   14.763 cycle/char,    0.216 Gc/s (3.6 %)     4.00 byte/char 
convert_utf32_to_latin1+westmere, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   0.469 ins/byte,    0.132 cycle/byte,   24.180 GB/s (1.5 %),     3.196 GHz,    3.548 ins/cycle 
   1.876 ins/char,    0.529 cycle/char,    6.045 Gc/s (1.5 %)     4.00 byte/char 
convert_utf32_to_latin1_with_errors+haswell, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   2.000 ins/byte,    0.327 cycle/byte,    9.772 GB/s (8.0 %),     3.194 GHz,    6.119 ins/cycle 
   8.001 ins/char,    1.307 cycle/char,    2.443 Gc/s (8.0 %)     4.00 byte/char 
convert_utf32_to_latin1_with_errors+icelake, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   0.188 ins/byte,    0.120 cycle/byte,   25.813 GB/s (0.8 %),     3.097 GHz,    1.564 ins/cycle 
   0.751 ins/char,    0.480 cycle/char,    6.453 Gc/s (0.8 %)     4.00 byte/char 
convert_utf32_to_latin1_with_errors+westmere, input size: 1729220, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.utflatin32.txt
   0.938 ins/byte,    0.225 cycle/byte,   14.203 GB/s (1.8 %),     3.195 GHz,    4.168 ins/cycle 
   3.751 ins/char,    0.900 cycle/char,    3.551 Gc/s (1.8 %)     4.00 byte/char 
```

Still need to do a little bit of cleanup but almost there.

### CODE REVIEW

**Comment by lemire** [comment]
Very good.

**Comment by lemire** [comment]
@Nick-Nuon Our random fuzzer seems to fail.

**Comment by lemire** [comment]
I am restarting the vs16 tests. They time out sometimes.

**Comment by lemire** [comment]
@Nick-Nuon Looks good. Can you clean the comments before we merge?

**Comment by Nick-Nuon** [comment]
> @Nick-Nuon Looks good. Can you clean the comments before we merge?

OK! I cleaned up the comments, and did clang-format. It should be good to go now.

**Comment by lemire** [comment]
I'll wait for the tests and merge.

**Pull request merged**
