### PR TITLE
Avx512 latin1 to utf32

### PR DESCRIPTION
**Pull request by Nick-Nuon**
Pinging because not sure where to go from there:  Mostly I riffed around the idea of using  _mm512_cvtepu8_epi32 as it seems to be tailor-made for exactly this situation so I'm not sure how I can improve upon it.

These are the benchmarks for this PR: 

For transparency, I also included the benchmarks for all the other attempts I made  ( in the PR itself, since it's a draft, I'll clean it up later). This time I did everything on the AVX512 servers: I note that SSE2 gives different (e.g. slightly worse) results than on my home PC.

```
/* convert_latin1_to_utf32+haswell, input size: 82168, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/esperanto.latin1.txt
   0.628 ins/byte,    0.373 cycle/byte,    8.615 GB/s (38.7 %),     3.209 GHz,    1.686 ins/cycle 
   0.628 ins/char,    0.373 cycle/char,    8.615 Gc/s (38.7 %)     1.00 byte/char 
WARNING: Measurements are noisy, try increasing iteration count (-I).
convert_latin1_to_utf32+icelake, input size: 82168, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/esperanto.latin1.txt
   0.316 ins/byte,    0.301 cycle/byte,   10.332 GB/s (5.0 %),     3.113 GHz,    1.049 ins/cycle 
   0.316 ins/char,    0.301 cycle/char,   10.332 Gc/s (5.0 %)     1.00 byte/char 
convert_latin1_to_utf32+iconv, input size: 82168, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/esperanto.latin1.txt
  32.031 ins/byte,    6.020 cycle/byte,    0.531 GB/s (0.3 %),     3.194 GHz,    5.321 ins/cycle 
  32.031 ins/char,    6.020 cycle/char,    0.531 Gc/s (0.3 %)     1.00 byte/char 
convert_latin1_to_utf32+icu, input size: 82168, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/esperanto.latin1.txt
  54.842 ins/byte,   10.695 cycle/byte,    0.299 GB/s (8.6 %),     3.193 GHz,    5.128 ins/cycle 
  54.842 ins/char,   10.695 cycle/char,    0.299 Gc/s (8.6 %)     1.00 byte/char 
convert_latin1_to_utf32+westmere, input size: 82168, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/esperanto.latin1.txt
   1.191 ins/byte,    0.252 cycle/byte,   12.759 GB/s (4.3 %),     3.221 GHz,    4.719 ins/cycle 
   1.191 ins/char,    0.252 cycle/char,   12.759 Gc/s (4.3 %)     1.00 byte/char 
input detected as unknown
current system detected as icelake
===========================
convert_latin1_to_utf32+haswell, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
   0.626 ins/byte,    0.587 cycle/byte,    5.443 GB/s (2.0 %),     3.196 GHz,    1.065 ins/cycle 
   0.626 ins/char,    0.587 cycle/char,    5.443 Gc/s (2.0 %)     1.00 byte/char 
convert_latin1_to_utf32+icelake, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
   0.313 ins/byte,    0.496 cycle/byte,    6.245 GB/s (2.0 %),     3.098 GHz,    0.631 ins/cycle 
   0.313 ins/char,    0.496 cycle/char,    6.245 Gc/s (2.0 %)     1.00 byte/char 
convert_latin1_to_utf32+iconv, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
  32.024 ins/byte,    6.026 cycle/byte,    0.530 GB/s (0.5 %),     3.193 GHz,    5.314 ins/cycle 
  32.024 ins/char,    6.026 cycle/char,    0.530 Gc/s (0.5 %)     1.00 byte/char 
convert_latin1_to_utf32+icu, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
  54.798 ins/byte,   10.710 cycle/byte,    0.298 GB/s (6.9 %),     3.189 GHz,    5.117 ins/cycle 
  54.798 ins/char,   10.710 cycle/char,    0.298 Gc/s (6.9 %)     1.00 byte/char 
convert_latin1_to_utf32+westmere, input size: 432305, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/french.latin1.txt
   1.188 ins/byte,    0.504 cycle/byte,    6.340 GB/s (0.9 %),     3.197 GHz,    2.356 ins/cycle 
   1.188 ins/char,    0.504 cycle/char,    6.340 Gc/s (0.9 %)     1.00 byte/char 
input detected as unknown
current system detected as icelake
===========================
convert_latin1_to_utf32+haswell, input size: 199331, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/german.latin1.txt
   0.626 ins/byte,    0.239 cycle/byte,   13.380 GB/s (1.9 %),     3.203 GHz,    2.616 ins/cycle 
   0.626 ins/char,    0.239 cycle/char,   13.380 Gc/s (1.9 %)     1.00 byte/char 
convert_latin1_to_utf32+icelake, input size: 199331, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/german.latin1.txt
   0.314 ins/byte,    0.251 cycle/byte,   12.387 GB/s (2.0 %),     3.103 GHz,    1.253 ins/cycle 
   0.314 ins/char,    0.251 cycle/char,   12.387 Gc/s (2.0 %)     1.00 byte/char 
convert_latin1_to_utf32+iconv, input size: 199331, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/german.latin1.txt
  32.026 ins/byte,    6.016 cycle/byte,    0.531 GB/s (0.3 %),     3.193 GHz,    5.323 ins/cycle 
  32.026 ins/char,    6.016 cycle/char,    0.531 Gc/s (0.3 %)     1.00 byte/char 
convert_latin1_to_utf32+icu, input size: 199331, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/german.latin1.txt
  54.809 ins/byte,   10.697 cycle/byte,    0.298 GB/s (9.0 %),     3.193 GHz,    5.124 ins/cycle 
  54.809 ins/char,   10.697 cycle/char,    0.298 Gc/s (9.0 %)     1.00 byte/char 
convert_latin1_to_utf32+westmere, input size: 199331, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/german.latin1.txt
   1.189 ins/byte,    0.258 cycle/byte,   12.407 GB/s (3.4 %),     3.203 GHz,    4.606 ins/cycle 
   1.189 ins/char,    0.258 cycle/char,   12.407 Gc/s (3.4 %)     1.00 byte/char 
input detected as unknown
current system detected as icelake
===========================
convert_latin1_to_utf32+haswell, input size: 271743, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/portuguese.latin1.txt
   0.626 ins/byte,    0.331 cycle/byte,    9.664 GB/s (1.8 %),     3.201 GHz,    1.890 ins/cycle 
   0.626 ins/char,    0.331 cycle/char,    9.664 Gc/s (1.8 %)     1.00 byte/char 
convert_latin1_to_utf32+icelake, input size: 271743, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/portuguese.latin1.txt
   0.314 ins/byte,    0.343 cycle/byte,    9.051 GB/s (2.9 %),     3.101 GHz,    0.916 ins/cycle 
   0.314 ins/char,    0.343 cycle/char,    9.051 Gc/s (2.9 %)     1.00 byte/char 
convert_latin1_to_utf32+iconv, input size: 271743, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/portuguese.latin1.txt
  32.025 ins/byte,    6.025 cycle/byte,    0.530 GB/s (0.4 %),     3.193 GHz,    5.316 ins/cycle 
  32.025 ins/char,    6.025 cycle/char,    0.530 Gc/s (0.4 %)     1.00 byte/char 
convert_latin1_to_utf32+icu, input size: 271743, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/portuguese.latin1.txt
  54.804 ins/byte,   10.705 cycle/byte,    0.298 GB/s (7.7 %),     3.193 GHz,    5.119 ins/cycle 
  54.804 ins/char,   10.705 cycle/char,    0.298 Gc/s (7.7 %)     1.00 byte/char 
convert_latin1_to_utf32+westmere, input size: 271743, iterations: 30000, dataset: /home/leorio/unicode_lipsum/wikipedia_mars/portuguese.latin1.txt
   1.189 ins/byte,    0.345 cycle/byte,    9.289 GB/s (2.7 %),     3.201 GHz,    3.449 ins/cycle 
   1.189 ins/char,    0.345 cycle/char,    9.289 Gc/s (2.7 %)     1.00 byte/char  */```

### CODE REVIEW

**Comment by lemire** [comment]
@Nick-Nuon 
We should be using something like 5 instructions per 16 bytes of input, so 0.3 instructions per byte and that's what you get.

The number of cycles per input by is surprisingly high... 

On [Ice Lake](https://uica.uops.info/?code=.L3%3A%0D%0A%20%20%20%20%20%20%20%20vpmovzxbd%20%20%20%20%20%20%20zmm0%2C%20XMMWORD%20PTR%20%5Brdi%2Brcx%5D%0D%0A%20%20%20%20%20%20%20%20vmovdqu64%20%20%20%20%20%20%20ZMMWORD%20PTR%20%5Brdx%2Brcx*4%5D%2C%20zmm0%0D%0A%20%20%20%20%20%20%20%20add%20%20%20%20%20rcx%2C%2016%0D%0A%20%20%20%20%20%20%20%20cmp%20%20%20%20%20rcx%2C%20rsi%0D%0A%20%20%20%20%20%20%20%20jb%20%20%20%20%20%20.L3%0D%0A&syntax=asIntel&uArchs=ICL&tools=uiCA&tools=llvm&tools=OSACA&alignment=0&uiCAHtmlOptions=dependencies), you should be bounded by port 5 (due to the loads). But obviously, that's not your bottleneck here.

**Comment by lemire** [comment]
@Nick-Nuon 


So this function, like many "to UTF-32" functions, is bounded by the requirement to write a lot of data.

When you see "5 GB/s" or "10 GB/s", consider that we report the speed in terms of the input. So to achieve 5 GB/s, we need to write at 20 GB/s. To achieve 10 GB/s, we need to write a 40 GB/s.

It gets difficult to exceed or even reach 40 GB/s in writing speed, and that's what we see here.

If you just break the code and keep only the stores:

```C++
     size_t i = 0;
     __m128i in = _mm_loadu_si128((__m128i*)&buf[i]);
     __m512i out = _mm512_cvtepu8_epi32(in);
    for (; i < rounded_len; i += 16) { 
        // Store the results back to memory
        _mm512_storeu_si512((__m512i*)&utf32_output[i], out);
    }
```

You go from 0.514 cycle/byte to 0.416 cycle/byte, so barely faster.

**Comment by lemire** [comment]
@Nick-Nuon I recommend cleaning your PR. We should merge it.

Good work.

**Comment by Nick-Nuon** [comment]
> @Nick-Nuon I recommend cleaning your PR. We should merge it.
> 
> Good work.

Cleaned it up a bit, I think she's good to go now.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
