### PR TITLE
feat(fuzz): Add more complete roundtrip fuzzing

### PR DESCRIPTION
**Pull request by silvergasp**
This change adds round-trip fuzzing to/from each encoding.

As an additional bonus, it removes at lease one large heap allocation so there should be a minor performance boost.

### CODE REVIEW

**Comment by silvergasp** [comment]
I've also iterated over each of the supported implementations as you suggested in https://github.com/google/oss-fuzz/pull/9942#issuecomment-1481912733

**Comment by silvergasp** [comment]
@lemire Should I close this? it looks like you have it covered in https://github.com/simdutf/simdutf/commit/5e7e1f75d35e8c4d5da323ff66d26944e39ed07d?

**Comment by lemire** [comment]
It looks similar to what I did independently, but it also looks like what you did is better so I think we will merge your PR.

**Comment by silvergasp** [comment]
> It looks similar to what I did independently, but it also looks like what you did is better so I think we will merge your PR.

Hmm maybe, though it looks like [the roundtrip equality checks in your additions](https://github.com/simdutf/simdutf/commit/5e7e1f75d35e8c4d5da323ff66d26944e39ed07d#diff-c30c860462fc7097dc002e2f38dc3cdbb0dedf348b44f1f61fbc2e2109d24ff1R95-R97) are probably valuable as well. I'll add similar checks in this PR and then I think we'll get the best of both worlds.

**Comment by lemire** [comment]
Please do. The end goal is to have as extensive testing as we can get.

**Comment by lemire** [comment]
Note that you should feel free to overwrite my changes, as long your changes are superior.

**Comment by lemire** [comment]
I am going to close this for now.

Feel free to contribute a better fuzzer.

**Pull request closed without merging**
