### PR TITLE
[NEON] Faster UTF-8 conversion routines

### PR DESCRIPTION
**Pull request by easyaspi314**
- Rewrite the intrinsics to be more NEON friendly
   - No longer a 1:1 translation of SSE4. While a generic algorithm is preferred, the common subset severely limits NEON's potential.
   - Use compound shifts, and bitwise selection to avoid `and; shr; orr`
      - Clang needs a hack to avoid constant propagating back to these.
   - Shuffle the 3 byte path in a way that is less clumsy for NEON (albeit a lot more confusing lol)
   - NEON has a very fast byte/word swap instruction, use it (applies to other functions too but I'm focusing here for now)
   - Make use of half vectors when appropriate (they can dual issue on little cores and have more favorable timing).
   - I can still do more micro-optimizations but I want to get feedback on this first. (I also want this before the half LUT, as I want the intrinsics to be optimized first)
 - Rework 4 byte sequence handling.
   - Completely rewritten.
   - Add a fast path for 3 or 4 4-byte sequences (the overhead for supporting both is like 2% since ARM doesn't need a branch). It is very worth it.
   - Calculate UTF-16 surrogates in parallel and skip the intermediate UTF-32
   - Use a blend mask to select the surrogate pairs
   - Use one magic addition to clear the UTF-8 prefix, adjust the surrogate offset, and add the surrogate prefixes
   - This new algorithm can be applied to SSE4/AVX2 with some tweaks.

### CODE REVIEW

**Comment by easyaspi314** [comment]
I do want to apply the 4 byte conversion rewrite to SSE4/AVX2 as well, the new approach is obviously faster from a rough draft, but I don't want to do too many things in one PR because my ADHD will go wild lol. (Also I am much less experienced in SSE anyways)

Do note that I plan on making more NEON optimization PRs.

**Comment by easyaspi314** [comment]
Still working on some Clang performance regressions.

**Comment by lemire** [comment]
> Do note that I plan on making more NEON optimization PRs.

They are certainly invited !!!

Of course, we want thorough benchmarks to make sure that it does move us forward.

I personally care very much about graviton 3 (neoverse) and Apple Silicon (+ Apple LLVM).

**Comment by lemire** [comment]
> While a generic algorithm is preferred

We are fine with dedicated algorithms. Of course, if there is no performance benefit to a specialized routine, we prefer to go generic... but when it pays to specialize, let us specialize.

I care a lot about ARM.

**Comment by easyaspi314** [comment]
I am still trying to work out some kinks in it. In theory it is better but GCC and Clang are both generating nonsense.

Issues:

 - Clang converts `usra` to `ushr; orr` or `ushr; add`
 - Clang converts `bsl` to `and; and; orr`
 - Inline assembly screws up instruction ordering
 - GCC reorders the compound in-place instructions in a way that forces it to use `mov`s everywhere.

**Comment by lemire** [comment]
I have avoided inline assembly, there is none in this project, deliberately.

**Comment by easyaspi314** [comment]
Noted. I might be able to get something passable with some simple empty asm statement guards, if that is okay. That can also be used to prevent GCC from reordering and screwing over the 4 byte paths. 

Also I was doing some tests. Apparently the slight slowdown is the branch for the 4 byte path. However, the dedicated path is **56% faster** when it comes to 3 or more 4 byte sequences. 

I can put it after the LUT load, which has some overhead from the redundant memory access but it is still much faster (43%) than not existing.

**Comment by lemire** [comment]
@easyaspi314 I recommend you do as you suggest, move it after the LUT. Then your PR becomes immediately an excellent candidate for merger... (I would need to read the code and do more benchmarks, more systems, more compilers, but I am quite optimistic that you already have something solid.) 

It always possible to come back for a second pass if you think it can be further improved.



Here is what I am getting on an M2 with the lipsum files... In three cases we get gains that are between ~5% and ~10%... which is fantastic if you ask me...

```
unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
unicode_lipsum/lipsum/Chinese-Lipsum.utf8.txt
unicode_lipsum/lipsum/Emoji-Lipsum.utf8.txt
unicode_lipsum/lipsum/Hebrew-Lipsum.utf8.txt
unicode_lipsum/lipsum/Hindi-Lipsum.utf8.txt
unicode_lipsum/lipsum/Japanese-Lipsum.utf8.txt
unicode_lipsum/lipsum/Korean-Lipsum.utf8.txt
unicode_lipsum/lipsum/Latin-Lipsum.utf8.txt
unicode_lipsum/lipsum/Russian-Lipsum.utf8.txt
```

main:
```
   4.374 ins/byte,    1.659 cycle/byte,    2.178 GB/s (4.5 %),     3.614 GHz,    2.636 ins/cycle
   3.932 ins/byte,    0.743 cycle/byte,    5.079 GB/s (1.4 %),     3.776 GHz,    5.289 ins/cycle
   7.135 ins/byte,    1.154 cycle/byte,    3.084 GB/s (2.1 %),     3.560 GHz,    6.181 ins/cycle
   4.422 ins/byte,    1.667 cycle/byte,    2.177 GB/s (4.2 %),     3.630 GHz,    2.653 ins/cycle
   4.661 ins/byte,    1.535 cycle/byte,    2.347 GB/s (2.8 %),     3.601 GHz,    3.038 ins/cycle
   4.097 ins/byte,    0.866 cycle/byte,    4.317 GB/s (2.0 %),     3.740 GHz,    4.729 ins/cycle
   5.150 ins/byte,    1.707 cycle/byte,    2.126 GB/s (0.7 %),     3.628 GHz,    3.018 ins/cycle
   0.593 ins/byte,    0.109 cycle/byte,   50.902 GB/s (8.7 %),     5.560 GHz,    5.426 ins/cycle
   4.172 ins/byte,    1.614 cycle/byte,    2.221 GB/s (1.0 %),     3.586 GHz,    2.584 ins/cycle
```

PR:
```
   4.636 ins/byte,    1.701 cycle/byte,    2.126 GB/s (6.0 %),     3.618 GHz,    2.725 ins/cycle
   3.775 ins/byte,    0.719 cycle/byte,    5.271 GB/s (2.0 %),     3.792 GHz,    5.247 ins/cycle
   3.840 ins/byte,    1.064 cycle/byte,    3.480 GB/s (4.1 %),     3.701 GHz,    3.611 ins/cycle
   4.684 ins/byte,    1.710 cycle/byte,    2.122 GB/s (6.5 %),     3.629 GHz,    2.739 ins/cycle
   4.740 ins/byte,    1.566 cycle/byte,    2.303 GB/s (5.7 %),     3.608 GHz,    3.026 ins/cycle
   3.982 ins/byte,    0.816 cycle/byte,    4.610 GB/s (6.2 %),     3.760 GHz,    4.882 ins/cycle
   5.404 ins/byte,    1.719 cycle/byte,    2.100 GB/s (13.6 %),     3.611 GHz,    3.143 ins/cycle
   0.593 ins/byte,    0.131 cycle/byte,   39.375 GB/s (9.6 %),     5.174 GHz,    4.510 ins/cycle
   4.403 ins/byte,    1.646 cycle/byte,    2.177 GB/s (1.3 %),     3.583 GHz,    2.675 ins/cycle
```

Putting the new branch *after* the LUT, as suggested by @easyaspi314

```
   4.371 ins/byte,    1.659 cycle/byte,    2.173 GB/s (3.9 %),     3.606 GHz,    2.634 ins/cycle
   3.671 ins/byte,    0.701 cycle/byte,    5.407 GB/s (1.0 %),     3.793 GHz,    5.233 ins/cycle
   4.556 ins/byte,    1.109 cycle/byte,    3.375 GB/s (8.6 %),     3.742 GHz,    4.110 ins/cycle
   4.418 ins/byte,    1.668 cycle/byte,    2.177 GB/s (9.1 %),     3.631 GHz,    2.649 ins/cycle
   4.532 ins/byte,    1.493 cycle/byte,    2.419 GB/s (11.5 %),     3.612 GHz,    3.035 ins/cycle
   3.858 ins/byte,    0.808 cycle/byte,    4.650 GB/s (3.9 %),     3.755 GHz,    4.778 ins/cycle
   5.117 ins/byte,    1.673 cycle/byte,    2.160 GB/s (1.3 %),     3.613 GHz,    3.060 ins/cycle
   0.593 ins/byte,    0.123 cycle/byte,   43.470 GB/s (7.1 %),     5.351 GHz,    4.814 ins/cycle
   4.163 ins/byte,    1.612 cycle/byte,    2.227 GB/s (0.8 %),     3.591 GHz,    2.582 ins/cycle
```

**Comment by easyaspi314** [comment]
I found a few more adjustments that I am cleaning up now.

I didn't find much luck on Clang without using inline assembly, as frustrating as it is. Apparently the issue occured from two consecutive `vbsl` intrinsics that depend on each other though. 

But I agree, I can always optimize this later. There is a lot of low hanging fruit that I should aim for first. 😅

**Comment by lemire** [comment]
My benchmarking was done with clang, so your optimization works with clang without any asm. Maybe not as well as you'd like, but it works. Bumping up Chinese from 5 GB/s to 5.4 GB/s is fantastic.

**Comment by easyaspi314** [comment]
The asm is wrapped in those macros. 

I am truly baffled as to why the 3 byte path is consistently much faster than the 2 byte path though 🤔

Constants aside the pure two byte is
```
rev16
and
sli
```
compared to
```
tbl
ext
sli
rev16
sli
```
And it writes half the data.

**Comment by lemire** [comment]
@easyaspi314 Here is the diff I applied to your PR (that's how I get the good results above):

```diff
diff --git a/src/arm64/arm_convert_utf8_to_utf16.cpp b/src/arm64/arm_convert_utf8_to_utf16.cpp
index f8e23fc..53c750b 100644
--- a/src/arm64/arm_convert_utf8_to_utf16.cpp
+++ b/src/arm64/arm_convert_utf8_to_utf16.cpp
@@ -83,7 +83,7 @@ size_t convert_masked_utf8_to_utf16(const char *input,
     utf16_output += 4;
     return 12;
   }
-  if(input_utf8_end_of_code_point_mask == 0x888) {
+/*  if(input_utf8_end_of_code_point_mask == 0x888) {
     // We want to take 3-4 4-byte UTF-8 words and turn them into 3-4 4-byte UTF-16 pairs.
     // Generating surrogate pairs is a little tricky though, but it is easier when we
     // can assume they are all pairs.
@@ -124,7 +124,7 @@ size_t convert_masked_utf8_to_utf16(const char *input,
     vst1q_u16(reinterpret_cast<uint16_t *>(utf16_output), composed);
     utf16_output += count * 2;
     return count * 4;
-  }
+  }*/
   /// We do not have a fast path available, so we fallback.
 
   const uint8_t idx =
@@ -191,6 +191,49 @@ size_t convert_masked_utf8_to_utf16(const char *input,
 
     utf16_output += 4;
   } else if (idx < 209) {
+    
+    if(input_utf8_end_of_code_point_mask == 0x888) {
+    // We want to take 3-4 4-byte UTF-8 words and turn them into 3-4 4-byte UTF-16 pairs.
+    // Generating surrogate pairs is a little tricky though, but it is easier when we
+    // can assume they are all pairs.
+    size_t count = 3 + ((utf8_end_of_code_point_mask & 0xFFFF) == 0x8888);
+    // Swap byte pairs
+    // 10dddddd 10cccccc|10bbbbbb 11110aaa
+    // 10cccccc 10dddddd|11110aaa 10bbbbbb
+    uint8x16_t swap1 = vrev16q_u8(in);
+    // Shift left 2 bits
+    // cccccc00 dddddd00 xxxxxxxx bbbbbb00
+    uint32x4_t shift = vreinterpretq_u32_u8(vshlq_n_u8(swap1, 2));
+    // Insert low 2 bits of trail surrogate to magic number for later
+
+    // UTF-8 4b prefix  = -0xF000|0000
+    // surrogate offset = -0x0040|0000 (0x10000 << 6)
+    // surrogate high   = +0xD800|0000
+    // surrogate low    = +0x0000|DC00
+    // -------------------------------
+    //                  = +0xE7C0|DC00
+    // 11011100 00000000 11100111 110000cc
+    uint16x8_t magic = vreinterpretq_u16_u32(VSRAQ_N_U32(vmovq_n_u32(0xDC00E7C0), shift, 30));
+    // Generate unadjusted trail surrogate minus lowest 2 bits
+    // xxxxxxxx xxxxxxxx|11110aaa bbbbbb00
+    uint32x4_t trail = VBSLQ_U32(vmovq_n_u32(0x0000FF00), swap1, shift);
+    // Generate lead surrogate
+    // xxxxcccc ccdddddd|xxxxxxxx xxxxxxxx
+    uint32x4_t lead = vsliq_n_u16(swap1, in, 6);
+    // Mask out lead
+    // 000000cc ccdddddd|xxxxxxxx xxxxxxxx
+    uint32x4_t masked = vbicq_u32(lead, vmovq_n_u32(0xFC000000));
+    // Blend pairs
+    // 000000cc ccdddddd|11110aaa bbbbbb00
+    uint16x8_t blend = vreinterpretq_u16_u32(VBSLQ_U32(vmovq_n_u32(0x0000FFFF), trail, masked));
+    // Add magic number to correct UTF-8 prefix, surrogate offset, and surrogate prefixes.
+    // 110111CC CCDDDDDD|110110AA BBBBBBCC
+    uint16x8_t composed = vaddq_u16(blend, magic);
+    if (!match_system(big_endian)) composed = vreinterpretq_u16_u8(vrev16q_u8(vreinterpretq_u8_u16(composed)));
+    vst1q_u16(reinterpret_cast<uint16_t *>(utf16_output), composed);
+    utf16_output += count * 2;
+    return count * 4;
+  }
     // TWO (2) input code-words
     uint8x16_t sh = vld1q_u8(reinterpret_cast<const uint8_t*>(simdutf::tables::utf8_to_utf16::shufutf8[idx]));
     // 1 byte: 00000000 00000000 00000000 0ddddddd
diff --git a/src/arm64/implementation.cpp b/src/arm64/implementation.cpp
index 838bd7b..89fc143 100644
--- a/src/arm64/implementation.cpp
+++ b/src/arm64/implementation.cpp
@@ -30,7 +30,7 @@ simdutf_really_inline simd8<bool> must_be_2_3_continuation(const simd8<uint8_t>
     return is_third_byte ^ is_fourth_byte;
 }
 
-#if defined(__clang__) && defined(__aarch64__)
+#if 0 && defined(__clang__) && defined(__aarch64__)
 // Clang tends to constant propagate these intrinsics into multiple instructions.
 // While it is true that BSL and SRA are slow, it is still the better option due to
 // how little time there is to wait for writeback.
```

So there is no inline assembly. In fact, enabling the inline assembly does not affect the performance.

```
 $ clang --version                                                            1
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
$ uname -a
Darwin DEP---CKJLG7D69H 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
```

I have not yet run it on graviton 3.

**Comment by easyaspi314** [comment]
New commit up. This makes some small tweaks, moves the 4 byte check down, fully comments, and removes the inline assembly.

**Comment by lemire** [comment]
On my todo to access.

**Comment by easyaspi314** [comment]
Hmm...I am seeing better performance with 6 codepoints instead of 8 for the 2 byte path. Long sequences of 2 byte sequences are kinda rare since the languages that use these have spaces, and 12 seems to get significantly more throughput for some reason even on a file of all 2 byte sequences where 16 should give 100% efficiency. 🤔 

Also why was I not benchmarking `convert_valid_utf8_to_utf16`... I didn't change error checking. So much benchmark noise I was unnecessarily putting up with 🤦‍♀️

**Comment by clausecker** [comment]
> Long sequences of 2 byte sequences are kinda rare since the languages that use these have spaces, and 12 seems to get significantly more throughput for some reason even on a file of all 2 byte sequences where 16 should give 100% efficiency.

Long sequences of 2 byte sequences are common e.g. with Arabic, Hebraic, and Russian as for these languages, all letters are encoded in 2 bytes.

**Comment by easyaspi314** [comment]
> > Long sequences of 2 byte sequences are kinda rare since the languages that use these have spaces, and 12 seems to get significantly more throughput for some reason even on a file of all 2 byte sequences where 16 should give 100% efficiency.
> 
> Long sequences of 2 byte sequences are common e.g. with Arabic, Hebraic, and Russian as for these languages, all letters are encoded in 2 bytes.

These languages use one byte spaces so they would actually only occur if you nail the middle of a word.

This is different from Chinese, Japanese, and Korean which almost exclusively use 3 byte characters.

**Comment by easyaspi314** [comment]
I was doing some more micro-optimizations and I yet again forgot to push because I got distracted by another project.

Specifically, I found ASCII conversion works better with `vst2` for ASCII->UTF16 and `vqtbl1q` for ASCII->UTF32. Also I was fiddling with some other things.

**Comment by lemire** [comment]
Note that this PR remains on my todo. It is not forgotten.

**Comment by easyaspi314** [comment]
Valid. I should push my latest changes I was talking about anyways, I got a really nice boost for ASCII.

**Comment by easyaspi314** [comment]
Version 3 is now up. ASCII is faster, I extracted some duplicate code, made sure everything is explained since intrinsics are hard to read, and did a few other tweaks.

I'm not gonna micro-optimize any more than this because I want to work on porting this to SSE2/AVX2 and working on some of the smaller stuff.

**Comment by lemire** [comment]
@easyaspi314 Great.

**Comment by easyaspi314** [comment]
Why ya gotta do me like this MSVC 😩

**Comment by lemire** [comment]
Not forgetting this.

**Comment by lemire** [comment]
Merging to temporary branch for further tests and manual benchmarks.

**Comment by lemire** [comment]
Merging to main branch. This is a worth optimization.

**Pull request merged**
