### PR TITLE
This adds new Latin 1 tests.

### PR DESCRIPTION
**Pull request by lemire**
It appears that the new Unicode => Latin 1 functions fail to return 0 for some invalid inputs.

Note: this code is unreleased.

### CODE REVIEW

**Comment by lemire** [comment]
@Nick-Nuon Can you have a look?

**Comment by Nick-Nuon** [comment]
> @Nick-Nuon Can you have a look?

I'm on it!

**Review by Nick-Nuon — APPROVED** [review]
Allright, I took a look at it . 
There were two issues: 
a) In utf8 => Latin1, there was an edge case which wasn't properly checked for
b) The validation functions under implementation validate a utfx string but not specifically for conversion to latin1.

(I wasn't sure how desirable validating utfX specifically for conversion to latin1 was a feature so I put it validation function from utfX => latin1 under simdutf::tests::references instead of under implementation.)

In any cases, all tests now pass.

**Comment by lemire** [comment]
Merging

**Pull request merged**
