### PR TITLE
Add missing copyright line to MIT license

### PR DESCRIPTION
**Pull request by lpinca**
Also break lines at 80 characters.

### CODE REVIEW

**Comment by lpinca** [comment]
If the 80 characters per line is not wanted I will revert it.

**Comment by lemire** [comment]
Can you explain why this is needed?

Here is the equivalent file in Rust...

https://github.com/rust-lang/rust/blob/master/LICENSE-MIT

**Comment by lpinca** [comment]
I'm not a lawyer but the license text says

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

If there is no copyright that sentence does not make much sense.

**Comment by lpinca** [comment]
The copyright line was removed from rust MIT license in this commit https://github.com/rust-lang/rust/commit/2a8807e889a43c6b89eb6f2736907afa87ae592f.

**Comment by lpinca** [comment]
There a bunch of MIT licenses here https://github.com/nodejs/node/blob/master/LICENSE and not a single one is missing the copyright notice. I'm not sure why rust decided to remove it.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
