### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by askeblad**
src/haswell/avx2_convert_utf16_to_utf8.cpp
src/simdutf/arm64/simd.h

src/westmere/sse_convert_utf16_to_utf8.cpp

### CODE REVIEW

**Comment by lemire** [comment]
Would you correct the same typo in [src/westmere/sse_convert_utf16_to_utf8.cpp](https://github.com/simdutf/simdutf/blob/4f6d4c6a89e3fba1fb60c55b8e05ec1f70b437c3/src/westmere/sse_convert_utf16_to_utf8.cpp)

**Comment by lemire** [comment]
I see you have, so nevermind.

**Comment by lemire** [comment]
I will be removing support for legacy windows, given that they are no longer supported by GitHub actions.

**Comment by askeblad** [comment]
_cf_: https://github.com/haskell/text/pull/426

**Comment by lemire** [comment]
Merging.

**Pull request merged**
