### PR TITLE
add length check for arm where UB sanitizer finds nullptr arithmetic

### PR DESCRIPTION
**Pull request by pauldreik**
There are probably more places that need this but I just fixed those that showed up when I fuzzed.

### CODE REVIEW

**Comment by pauldreik** [comment]
There is one more to fix:

> /home/fuzzer/code/simdutf/src/arm64/arm_convert_latin1_to_utf8.cpp:13:23: runtime error: applying non-zero offset 16 to null pointer

**Comment by lemire** [comment]
@pauldreik Merged and did other fixes in the main branch.

**Comment by lemire** [comment]
@pauldreik 

We have a new release.

Unfortunately, oss-fuzz seems to be broken. :-/

**Comment by pauldreik** [comment]
The oss fuzz build error is this:
```Step #3 - "compile-afl-address-x86_64": [ 50%] Building CXX object src/CMakeFiles/simdutf.dir/simdutf.cpp.o
Step #3 - "compile-afl-address-x86_64": In file included from /src/simdutf/src/simdutf.cpp:64:
Step #3 - "compile-afl-address-x86_64": In file included from /src/simdutf/src/icelake/implementation.cpp:24:
Step #3 - "compile-afl-address-x86_64": /src/simdutf/src/icelake/icelake_from_utf8.inl.cpp:266:20: fatal error: expected expression
Step #3 - "compile-afl-address-x86_64":   266 |     if (end - ptr => 64) {
Step #3 - "compile-afl-address-x86_64":       |                    ^
Step #3 - "compile-afl-address-x86_64": 1 error generated.
Step #3 - "compile-afl-address-x86_64": make[2]: *** [src/CMakeFiles/simdutf.dir/build.make:76: src/CMakeFiles/simdutf.dir/simdutf.cpp.o] Error 1
```

which looks like a real problem. Or was there some other problem you refer to? Maybe we can add myself to the oss-fuzz cc list, so I can see problems without waiting 90 days.

**Comment by lemire** [comment]
> which looks like a real problem. 

That was a temporary bug I introduced. The current release should be fine. :-)

> Or was there some other problem you refer to? 

I have not investigated. Maybe there is just a delay.

> Maybe we can add myself to the oss-fuzz cc list, so I can see problems without waiting 90 days.

Please do. Or I can do it if you tell me how.

**Pull request merged**
