### PR TITLE
Adds UTF-32 and ASCII validation (AVX-512).

### PR DESCRIPTION
**Pull request by NicolasJiaxin**

### CODE REVIEW

**Comment by NicolasJiaxin** [comment]
I imported the code for UTF-32 validation. Unfortunately, I am again the bearer of "bad numbers". These are the numbers I get on the benchmarks,

||fallback|haswell|icelake|westmere|
|-|-|-|-|-|
|Arabic-Lipsum.utf32.txt|2.329|9.249|7.181|6.967|
|Chinese-Lipsum.utf32.txt|2.325|9.233|7.196|6.935|
|Emoji-Lipsum.utf32.txt|2.320|9.195|7.202|6.905|
|Hebrew-Lipsum.utf32.txt|2.328|9.241|7.390|6.962|
|Hindi-Lipsum.utf32.txt|2.327|9.243|7.174|6.956|
|Japanese-Lipsum.utf32.txt|2.325|9.235|7.166|6.934|
|Korean-Lipsum.utf32.txt|2.326|9.236|7.158|6.940|
|Latin-Lipsum.utf32.txt|2.331|9.235|7.145|6.979|
|Russian-Lipsum.utf32.txt|2.329|9.253|7.154|6.969|

Granted that I did not do anything special and the AVX-512 is the same as haswell and westmere, it is already pretty efficient I would think. Excluding the load, there are three cheap function calls (two max, and one add) per 512 bits of data.

**Comment by lemire** [comment]
Yes. It should be efficient. You could tweak your code a bit to save an instruction within the loop, but it is unlikely to be the issue... your code should be at least as fast as the AVX code. I think we should quickly merge it... but I might want to investigate a bit.

**Comment by lemire** [comment]
I confirm your results. Interesting.

**Comment by lemire** [comment]
+1 for the ternary !

**Comment by NicolasJiaxin** [comment]
> You could tweak your code a bit to save an instruction within the loop

Were you referring to the ternary in the ASCII loop or for the UTF-32 validation loop?

**Comment by lemire** [comment]
> Were you referring to the ternary in the ASCII loop or for the UTF-32 validation loop?

Nope. Let elaborate.

(I do not think that's the issue you need to care about.)

**Comment by lemire** [comment]
Ok. Here is the tight loop with gcc 12:
```asm
   0x00000000000346f0 <+64>:    vpaddd -0x40(%rax),%zmm4,%zmm0
   0x00000000000346f7 <+71>:    vpmaxud -0x40(%rax),%zmm2,%zmm1
   0x00000000000346fe <+78>:    add    $0x40,%rax
   0x0000000000034702 <+82>:    vpmaxud %zmm3,%zmm0,%zmm0
   0x0000000000034708 <+88>:    vmovdqa64 %zmm1,%zmm2
   0x000000000003470e <+94>:    vmovdqa64 %zmm0,%zmm3
   0x0000000000034714 <+100>:   cmp    %rcx,%rax
   0x0000000000034717 <+103>:   jbe    0x346f0 <simdutf::icelake::implementation::validate_utf32(char32_t const*, unsigned long) const+64>
```

It looks like a mess to me.

**Comment by lemire** [comment]
So here are our numbers with clang 14:

```
$ ./buildclang/benchmarks/benchmark -P validate_utf32 -F unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
validate_utf32+fallback, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   1.748 GB/s (1.0 %)    1.748 Gc/s     1.00 byte/char 
validate_utf32+haswell, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   8.687 GB/s (7.9 %)    8.687 Gc/s     1.00 byte/char 
validate_utf32+icelake, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
  12.928 GB/s (2.4 %)   12.928 Gc/s     1.00 byte/char 
validate_utf32+westmere, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   5.401 GB/s (1.7 %)    5.401 Gc/s     1.00 byte/char 
```

Here is gcc 12...

```
$ ./build/benchmarks/benchmark -P validate_utf32 -F unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
validate_utf32+fallback, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   2.329 GB/s (0.6 %)    2.329 Gc/s     1.00 byte/char 
validate_utf32+haswell, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   9.242 GB/s (1.8 %)    9.242 Gc/s     1.00 byte/char 
validate_utf32+icelake, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   7.173 GB/s (2.2 %)    7.173 Gc/s     1.00 byte/char 
validate_utf32+westmere, input size: 183056, iterations: 2000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf32.txt
   6.968 GB/s (3.5 %)    6.968 Gc/s     1.00 byte/char 
```

So I have shown that it is a code generation issue.

**Comment by lemire** [comment]
Here is the code generated by clang...

```asm
   0x0000000000036ab0 <+48>:    vmovdqu64 (%rdi),%zmm3
   0x0000000000036ab6 <+54>:    vpmaxud %zmm1,%zmm3,%zmm1
   0x0000000000036abc <+60>:    vpaddd %zmm2,%zmm3,%zmm3
   0x0000000000036ac2 <+66>:    vpmaxud %zmm0,%zmm3,%zmm0
   0x0000000000036ac8 <+72>:    lea    0x40(%rdi),%rcx
   0x0000000000036acc <+76>:    sub    $0xffffffffffffff80,%rdi
   0x0000000000036ad0 <+80>:    cmp    %rax,%rdi
   0x0000000000036ad3 <+83>:    mov    %rcx,%rdi
   0x0000000000036ad6 <+86>:    jbe    0x36ab0 <_ZNK7simdutf7icelake14implementation14validate_utf32EPKDim+48>
```

**Comment by lemire** [comment]
It is a case where GCC does a poor job. Short of writing your own assembly (like @clausecker  might do), there could be little we can do. Thankfully,  7 GB/s is still quite fast. It is a shame that clang can reach almost double *with the same code*.

We should report it to the GCC folks.

**Comment by lemire** [comment]
@NicolasJiaxin 

Consider the following patch...

```diff
index e227aaa..135c5f2 100644
--- a/src/icelake/implementation.cpp
+++ b/src/icelake/implementation.cpp
@@ -65,16 +65,16 @@ simdutf_warn_unused bool implementation::validate_utf16(const char16_t *buf, siz
 
 simdutf_warn_unused bool implementation::validate_utf32(const char32_t *buf, size_t len) const noexcept {
     const char32_t* ptr = buf;
-    const char32_t* end = ptr + len;
-
+    const char32_t* end = len >= 16 ? buf + len - 16 : nullptr;
     const __m512i offset = _mm512_set1_epi32((uint32_t)0xffff2000);
     __m512i currentmax = _mm512_setzero_si512();
     __m512i currentoffsetmax = _mm512_setzero_si512();
 
-    for (; ptr + 16 <= end; ptr += 16) {
-        const __m512i utf32 = _mm512_loadu_si512((const __m512i*)ptr);
-        currentmax = _mm512_max_epu32(utf32, currentmax);
-        currentoffsetmax = _mm512_max_epu32(_mm512_add_epi32(utf32, offset), currentoffsetmax);
+    while (ptr <= end) {
+         __m512i utf32 = _mm512_loadu_si512((const __m512i*)ptr);
+         ptr += 16;
+         currentoffsetmax = _mm512_max_epu32(_mm512_add_epi32(utf32, offset), currentoffsetmax);
+         currentmax = _mm512_max_epu32(utf32, currentmax);
     }
 
     const __m512i standardmax = _mm512_set1_epi32((uint32_t)0x10ffff);
```

With this patch, I am getting the following GCC tight loop...

```asm
0x00000000000346e8 <+56>:    vmovdqu64 (%rax),%zmm0
   0x00000000000346ee <+62>:    add    $0x40,%rax
   0x00000000000346f2 <+66>:    vpaddd %zmm0,%zmm4,%zmm1
   0x00000000000346f8 <+72>:    vpmaxud %zmm0,%zmm2,%zmm0
   0x00000000000346fe <+78>:    vpmaxud %zmm3,%zmm1,%zmm1
   0x0000000000034704 <+84>:    vmovdqa64 %zmm0,%zmm2
   0x000000000003470a <+90>:    vmovdqa64 %zmm1,%zmm3
   0x0000000000034710 <+96>:    cmp    %rax,%rcx
   0x0000000000034713 <+99>:    jae    0x346e8 <_ZNK7simdutf7icelake14implementation14validate_utf32EPKDim+56>
```

and the following clang tight loop...

```asm
   0x0000000000036ac0 <+64>:    vmovdqu64 (%rcx),%zmm3
   0x0000000000036ac6 <+70>:    add    $0x40,%rcx
   0x0000000000036aca <+74>:    vpaddd %zmm2,%zmm3,%zmm4
   0x0000000000036ad0 <+80>:    vpmaxud %zmm0,%zmm4,%zmm0
   0x0000000000036ad6 <+86>:    vpmaxud %zmm1,%zmm3,%zmm1
   0x0000000000036adc <+92>:    cmp    %rax,%rcx
   0x0000000000036adf <+95>:    jbe    0x36ac0 <_ZNK7simdutf7icelake14implementation14validate_utf32EPKDim+64>
```

I am not exactly sure why GCC has the two additional register-to-register moves, but it is likely exactly (literally) free due to register renaming.

**Comment by lemire** [comment]
I expect that my patch my solve the GCC performance issue.

**Comment by lemire** [comment]
> I found a related issue: https://stackoverflow.com/questions/61308501/why-does-gcc-add-extra-vmovdqa64-instructions-with-mm512-dpbusds-epi32. Seems to be a bug.

Good catch.

So it is an old bug... https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94663

It is hard to tell for sure, but I expect that it does not have performance effects, as far as we are concerned.

**Comment by lemire** [comment]
I am merging into the AVX-512 branch now.

**Pull request merged**
