### PR TITLE
reenabling RVV ci

### PR DESCRIPTION
**Pull request by lemire**
Let us make sure our tests pass.

cc @WojciechMula

### CODE REVIEW

**Comment by lemire** [comment]
Maybe the failure is due to a typo.

**Comment by WojciechMula** [comment]
> Maybe the failure is due to a typo.

Seems like RISC-V code of amalgamation was executed on the host machine.

**Comment by lemire** [comment]
> Seems like RISC-V code of amalgamation was executed on the host machine.

Yes. I think we are going to be good now.

**Comment by lemire** [comment]
We are good. Merging.

**Pull request merged**
