### PR TITLE
fix: try reenabling RISC-V CI

### PR DESCRIPTION
**Pull request by lemire**
Fixes https://github.com/simdutf/simdutf/issues/385

(Hopeful)

cc @WojciechMula

### CODE REVIEW

**Comment by lemire** [comment]
@WojciechMula I have forced pushed an update but I suspect that the RVV code might have bugs... :-(

**Comment by WojciechMula** [comment]
@lemire I'll look at this.

**Comment by camel-cdr** [comment]
@lemire  Somehow I didn't get notified by your issue, where you mentioned me. I'll also try to look into this in the weekend.

**Comment by lemire** [comment]
The issue may or may not be indicative of a bug... but we are struggling to run tests, that is clear.

**Comment by WojciechMula** [comment]
I'm having errors when run in Spike simulator, so it will be easy to track down the cause.

**Comment by WojciechMula** [comment]
Just a quick update, as I'm running out of time this week. I was working on bug in utf16 -> utf32 -- there's a problem with surrogates handling. I fixed it (and later discovered we have similar approach in the AVX-512 variant). But I think I discovered a problem with UTF-16 validation.

**Comment by lemire** [comment]
@WojciechMula Thankfully, I don't expect that anyone is running this code in production... yet... :-)

**Comment by WojciechMula** [comment]
> But I think I discovered a problem with UTF-16 validation.

Good, I just didn't understand AVX-512 validation.

**Comment by lemire** [comment]
Closing in favour of https://github.com/simdutf/simdutf/pull/413

**Pull request closed without merging**
