### PR TITLE
minor maintenance for runtime dispatching

### PR DESCRIPTION
**Pull request by lemire**
When you can always run a kernel, then we do not need annotation. This may lead to spurious warnings on some systems.

### CODE REVIEW

**Comment by Jarred-Sumner** [comment]
Would this resolve the `#pragma clang pop` error?

https://github.com/oven-sh/bun/issues/1690#issuecomment-1368506392

**Comment by lemire** [comment]
Yes. It very well might, if not let us know. This PR was meant to silence that particular warning. Note that it should not be an error but a warning.

**Comment by lemire** [comment]
I’ll merge and issue a release soon.

**Comment by lemire** [comment]
@Jarred-Sumner Released: https://github.com/simdutf/simdutf/releases/tag/v2.1.0

**Pull request merged**
