### PR TITLE
verify issue 468

### PR DESCRIPTION
**Pull request by lemire**
Trying to verify issue 468

cc @pauldreik

### CODE REVIEW

**Comment by lemire** [comment]
@pauldreik Can you help me verify the issue?

**Comment by pauldreik** [comment]
> @pauldreik Can you help me verify the issue?

yes

**Comment by pauldreik** [comment]
When I build with 

> cmake -DCMAKE_BUILD_TYPE=Debug -DSIMDUTF_SANITIZE_UNDEFINED=On -GNinja -B blah-clang -S . -DCMAKE_CXX_COMPILER=/usr/lib/ccache/clang++-18


I get the following output:

> Running 'allow empty input'... /tmp/issue468/simdutf/src/haswell/avx2_convert_utf16_to_utf32.cpp:129:14: runtime error: applying non-zero offset 32 to null pointer

I do however not get that with gcc.

**Comment by pauldreik** [comment]
I submitted a PR for gcc failures separately: https://github.com/simdutf/simdutf/pull/474

**Comment by pauldreik** [comment]
I also reproduced this with clang 17 and clang 16.

**Comment by lemire** [comment]
> I also reproduced this with clang 17 and clang 16.

Hmmm.... Not reproduced with Fedora 40 with LLVM 18.

Let me try with Apple LLVM.

**Pull request merged**
