### PR TITLE
update RVV CI

### PR DESCRIPTION
**Pull request by camel-cdr**
~~Since GCC version 14 it's possible to use the target region attribute for RVV intrinsics: https://godbolt.org/z/KbGxa8Tfz~~

If all goes well, we should be able to just test for v1.0 support of the RVV intrinsics via `__riscv_v_intrinsic >= 1000000` in the future: https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/376

### CODE REVIEW

**Comment by lemire** [comment]
@camel-cdr Could we run our CI tests with GCC ?

https://github.com/simdutf/simdutf/blob/master/.github/workflows/rvv-128-clang-17.yml

**Comment by camel-cdr** [comment]
@lemire I thought this worked, but I didn't test it correctly. Turns out the target region thing still has problems even on clang-20 and gcc-14 ICEs.
So for now it's only supported without target region, so when march includes "v".

**Comment by camel-cdr** [comment]
Looks like it timed out again. It works for me locally with clang-18 and the same setting, so I tried increasing the timeout slightly.

**Comment by lemire** [comment]
I think we are good now. Merging. The lint can be done later.

**Pull request merged**
