### PR TITLE
Optimize AVX512 detect_encodings implementation

### PR DESCRIPTION
**Pull request by tantei3**
Implementing #528 for Icelake.

Read the data only once and maintain the bodies of UTF8, UTF16LE and UTF32LE checker inlined inside the routine and feed each 64 byte input block once.

The UTF16LE routine is slightly modified to avoid checks and separately maintain the high surrogate ending state. All unit tests for detect_encodings seems to be passing.

Still this probably needs more careful review and I'm not sure if mathematically it is correct at the moment. Not sure about the speed-up either.

If this design and implementation is good, then separately the rest of x86 can be updated.

### CODE REVIEW

**Comment by lemire** [comment]
Wow! ❤️ 

Let us run the tests.

**Comment by lemire** [comment]
(Note: this needs to be manually checked before merging because the CI runners are likely skipping AVX-512.)

**Comment by lemire** [comment]
I've manually reviewed it. I will merge and then run more tests.

**Comment by pauldreik** [comment]
I ran the fuzzers on icelake b0239a8dcfa578ccd77a7c10632d0fb7837d2836 and it unfortunately fails with what seems to be two distinct symptoms: overshift and out of bounds read.
this is the output from the fuzzer:

```
Running: crash-e2aaa20fd70efecc2e0d89955fc4160c06522fd5
/home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:91:20: runtime error: shift exponent 64 is too large for 64-bit type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:91:20 
=================================================================
==121476==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x502000000334 at pc 0x558f11da1346 bp 0x7ffe5d493830 sp 0x7ffe5d493828
READ of size 1 at 0x502000000334 thread T0
    #0 0x558f11da1345 in simdutf::icelake::implementation::detect_encodings(char const*, unsigned long) const /home/pauldreik/code/delaktig/simdutf/src/icelake/implementation.cpp:90:24
    #1 0x558f11d5001f in detect(std::span<char const, 18446744073709551615ul>) /home/pauldreik/code/delaktig/simdutf/fuzz/misc.cpp:30:29
    #2 0x558f11d55bc4 in LLVMFuzzerTestOneInput /home/pauldreik/code/delaktig/simdutf/fuzz/misc.cpp:181:5

```

here is the crash data:
```
pauldreik@privat-kodning:~/code/delaktig/simdutf/fuzz$ base64 <crash-e2aaa20fd70efecc2e0d89955fc4160c06522fd5
AQA9Cg==
```

I built the fuzzer with CXXFLAGS="-fsanitize=fuzzer-no-link,address,undefined -g -O3" by modifying this line before building: https://github.com/simdutf/simdutf/blob/b0239a8dcfa578ccd77a7c10632d0fb7837d2836/fuzz/build.sh#L20

**Comment by tantei3** [comment]
Will address this as part of #627

**Pull request merged**
