### PR TITLE
Fixing support for Windows ARM64

### PR DESCRIPTION
**Pull request by lemire**
@StefanStojanovic could you test/review?

Capture d’écran, le 2023-02-22 à 16 49 07

Capture d’écran, le 2023-02-22 à 16 49 45

Fixes https://github.com/simdutf/simdutf/issues/216

### CODE REVIEW

**Comment by StefanStojanovic** [comment]
@lemire I'm still experiencing the same behavior from https://github.com/simdutf/simdutf/issues/216, but I also saw that all checks from your CI passed.

From what I can tell, the biggest difference between our runs is that I'm using VS16 (VS 2019) while you are using VS17 (VS 2022). Could you try building and running tests with VS16 and see what happens? The thing here is that in Node.js CI we're using VS 2019 for building on Windows.

FYI, I'm OOF for the rest of the week, but I'll try to follow this as time allows.

**Comment by lemire** [comment]
Ok. Let me try with an older Visual Studio.

**Comment by lemire** [comment]
@StefanStojanovic Ok. Older Visual Studios are not supported on ARM64 and requires cross-compiling.

Checking the cross-compilation.

**Comment by lemire** [comment]
So here is what I did. I went on an x64 machine. I made use that I had both VS 2019 and VS 2022 installed. I then cross-compiled the project.

```
cmake -G "Visual Studio 16 2019" -A ARM64  -DCMAKE_CROSSCOMPILING=1 -B buildarmold
cmake --build buildarmold
```

(If you want the more recent Visual Studio, you have to use "Visual Studio 17 2022" instead.)

It built various files. I tend uploaded the files to my ARM64 machine and I ran the files, and they ran fine.

You can download the files in question from my Google Drive...

https://drive.google.com/drive/folders/123o3hC2Ws-_cY_AuPyUHH8CuxCxouZ_F?usp=share_link

**Pull request merged**
