### PR TITLE
preparing release 5.3.2

### PR DESCRIPTION
**Pull request by lemire**
After merging this PR, we will release version 5.3.2.

### CODE REVIEW

**Comment by pauldreik** [comment]
I think I have one more finding, you might want to hold off the release just a minute while I see if it is real or not.

**Comment by lemire** [comment]
@pauldreik Waiting.

**Comment by pauldreik** [comment]
see #478

**Comment by pauldreik** [comment]
I found #479 as well

**Comment by lemire** [comment]
@pauldreik Thanks. Let us fix those before the release. If you find more, please don't hesitate to ping me.

**Comment by pauldreik** [comment]
I can't find anything more in the convert_* family of functions for now (tested on arm and icelake).

**Comment by lemire** [comment]
@pauldreik Thanks. I believe I have addressed all of these issues. I am resyncing this pre-release PR.

Don't be shy about reporting new issues.

**Pull request merged**
