### PR TITLE
issue 578

### PR DESCRIPTION
**Pull request by lemire**
Some versions of GCC  appear to get confused when compiling `operator==` in debug mode for the haswell kernel (but seemingly, not other kernels?). Though the functions are declared and defined in a region where AVX support is guaranteed, and is only used in such a context, it complains of a 'target specific option mismatch'. More recent versions of GCC (13+) do not have this problem, nor does LLVM as far as I can tell.

To get around the issue, we force inline two specific functions.

Thanks to @hansingt for the report.

Fixes https://github.com/simdutf/simdutf/issues/578

### CODE REVIEW

**Comment by lemire** [comment]
I did not lint it, but I will do so later.

**Comment by lemire** [comment]
@hansingt  This will be part of our next release.

**Comment by lemire** [comment]
@hansingt Feel free to verify the fix right now.

**Comment by hansingt** [comment]
@lemire Thanks for the quick fix. I've verified, that compilation now works 👍️

Now I'm eagerly awaiting the next release 😊

**Pull request merged**
