### PR TITLE
Adding the base64 decode with garbage option code changes

### PR DESCRIPTION
**Pull request by tantei3**
Adds the functionality described in #585 
Includes the unit tests written in #600 and the extra couple lines of fixes described there.
The tests are passing locally (on x86_64), rest architectures might need fixes if failures are detected.

### CODE REVIEW

**Comment by lemire** [comment]
Wow !!!

**Comment by lemire** [comment]
Merging.

**Comment by tantei3** [comment]
Thanks for merging! I was wondering if it would be better for performance if the ignore garbage variable should be a template variable (similar to base64_url) for performance, since it seems to be adding a lot of branches checks. Any thoughts on whether we should move it to be a compile time known constant so that branches can be better optimized at the cost of slight code bloat?

**Comment by lemire** [comment]
@tantei3 Yes. I think we should.

**Pull request merged**
