### PR TITLE
AVX512 feature branch (legacy)

### PR DESCRIPTION
**Pull request by lemire**
This is a feature branch for AVX512 implementations. It will not be merged. Instead, we are working on https://github.com/simdutf/simdutf/pull/174 with the new (extended) simdutf API.

For the time being, it will remain for benchmarking and testing purposes.

### CODE REVIEW

**Comment by lemire** [comment]
@WojciechMula I have now brought everything in the simdutf, in this branch, for further work.

**Comment by lemire** [comment]
cc @WojciechMula : This is now up-to-date with lookup4 validation... which is a really nice win.

**Comment by lemire** [comment]
It might be more reasonable to require VBMI2.

**Comment by clausecker** [comment]
The auto detection seems to be broken.  It detects the Icelake system as as a Haswell and the speed measured is suspiciously low.

**Comment by lemire** [comment]
> The auto detection seems to be broken.

Something is broken in the benchmark program, but I suspect that the bug existed before (it is probably present in our main branch). As far as I can tell, our automatic detection works... but unsupported kernels are not excluded as part of the benchmark...

**Comment by lemire** [comment]
@clausecker I fixed it. The benchmarking program should be slightly more robust now.

**Comment by lemire** [comment]
@clausecker I am currently trying to figure out whether I made a mistake somewhere. The code is correct, but it seems that the performance is disappointing. I am not sure why yet.

**Comment by clausecker** [comment]
For adding my own changes, I suppose I just make a PR against the avx512feature branch, adding my code to the src/avx512vbmi directory?

**Comment by lemire** [comment]
> For adding my own changes, I suppose I just make a PR against the avx512feature branch, adding my code to the src/avx512vbmi directory? 

That would be great. Do not hesitate to call for help, as it can be a bit confusing (i.e., if you encounter problems, it is not necessarily because you are being silly).

**Comment by lemire** [comment]
I am going to try to figure out the performance numbers for the 'from utf-8'. It should be better than what I am seeing right now.

**Comment by lemire** [comment]
> For adding my own changes, I suppose I just make a PR against the avx512feature branch, adding my code to the src/avx512vbmi directory?

Actually... no... please start from the current branch (avx512feature). So you should look at 'src/icelake'. I think you are studying older branches.

**Comment by lemire** [comment]
The new numbers.... (they are better)

```
$ for i in  unicode_lipsum/lipsum/*.utf8.txt ; do ./build/benchmarks/benchmark -P convert_utf8_to_utf16+haswell -P convert_utf8_to_utf16+icelake -F $i -I 10000; done
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 81685, iterations: 10000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
   2.388 GB/s (1.2 %)    1.338 Gc/s     1.78 byte/char 
convert_utf8_to_utf16+icelake, input size: 81685, iterations: 10000, dataset: unicode_lipsum/lipsum/Arabic-Lipsum.utf8.txt
   3.385 GB/s (2.7 %)    1.896 Gc/s     1.78 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 69840, iterations: 10000, dataset: unicode_lipsum/lipsum/Chinese-Lipsum.utf8.txt
   3.823 GB/s (1.3 %)    1.284 Gc/s     2.98 byte/char 
convert_utf8_to_utf16+icelake, input size: 69840, iterations: 10000, dataset: unicode_lipsum/lipsum/Chinese-Lipsum.utf8.txt
   3.954 GB/s (1.0 %)    1.328 Gc/s     2.98 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 65542, iterations: 10000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf8.txt
   1.581 GB/s (1.1 %)    0.395 Gc/s     4.00 byte/char 
convert_utf8_to_utf16+icelake, input size: 65542, iterations: 10000, dataset: unicode_lipsum/lipsum/Emoji-Lipsum.utf8.txt
   3.130 GB/s (0.8 %)    0.783 Gc/s     4.00 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 66495, iterations: 10000, dataset: unicode_lipsum/lipsum/Hebrew-Lipsum.utf8.txt
   2.390 GB/s (1.0 %)    1.341 Gc/s     1.78 byte/char 
convert_utf8_to_utf16+icelake, input size: 66495, iterations: 10000, dataset: unicode_lipsum/lipsum/Hebrew-Lipsum.utf8.txt
   3.360 GB/s (1.0 %)    1.885 Gc/s     1.78 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 87997, iterations: 10000, dataset: unicode_lipsum/lipsum/Hindi-Lipsum.utf8.txt
   2.575 GB/s (1.4 %)    0.959 Gc/s     2.69 byte/char 
convert_utf8_to_utf16+icelake, input size: 87997, iterations: 10000, dataset: unicode_lipsum/lipsum/Hindi-Lipsum.utf8.txt
   3.958 GB/s (0.7 %)    1.474 Gc/s     2.69 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 67808, iterations: 10000, dataset: unicode_lipsum/lipsum/Japanese-Lipsum.utf8.txt
   3.556 GB/s (1.3 %)    1.226 Gc/s     2.90 byte/char 
convert_utf8_to_utf16+icelake, input size: 67808, iterations: 10000, dataset: unicode_lipsum/lipsum/Japanese-Lipsum.utf8.txt
   3.977 GB/s (0.8 %)    1.371 Gc/s     2.90 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 66600, iterations: 10000, dataset: unicode_lipsum/lipsum/Korean-Lipsum.utf8.txt
   2.196 GB/s (1.1 %)    0.895 Gc/s     2.45 byte/char 
convert_utf8_to_utf16+icelake, input size: 66600, iterations: 10000, dataset: unicode_lipsum/lipsum/Korean-Lipsum.utf8.txt
   3.960 GB/s (0.8 %)    1.614 Gc/s     2.45 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 86940, iterations: 10000, dataset: unicode_lipsum/lipsum/Latin-Lipsum.utf8.txt
  21.850 GB/s (2.6 %)   21.850 Gc/s     1.00 byte/char 
convert_utf8_to_utf16+icelake, input size: 86940, iterations: 10000, dataset: unicode_lipsum/lipsum/Latin-Lipsum.utf8.txt
  24.332 GB/s (3.5 %)   24.332 Gc/s     1.00 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 104770, iterations: 10000, dataset: unicode_lipsum/lipsum/Russian-Lipsum.utf8.txt
   2.473 GB/s (1.0 %)    1.369 Gc/s     1.81 byte/char 
convert_utf8_to_utf16+icelake, input size: 104770, iterations: 10000, dataset: unicode_lipsum/lipsum/Russian-Lipsum.utf8.txt
   3.285 GB/s (0.9 %)    1.818 Gc/s     1.81 byte/char 

$  for i in  unicode_lipsum/wikipedia_mars/*.utf8.txt ; do ./build/benchmarks/benchmark -P convert_utf8_to_utf16+haswell -P convert_utf8_to_utf16+icelake -F $i -I 10000; done
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 533857, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/arabic.utf8.txt
   3.174 GB/s (2.5 %)    2.526 Gc/s     1.26 byte/char 
convert_utf8_to_utf16+icelake, input size: 533857, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/arabic.utf8.txt
   4.153 GB/s (1.4 %)    3.305 Gc/s     1.26 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 181321, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/chinese.utf8.txt
   3.057 GB/s (4.5 %)    2.313 Gc/s     1.32 byte/char 
convert_utf8_to_utf16+icelake, input size: 181321, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/chinese.utf8.txt
   4.032 GB/s (0.8 %)    3.051 Gc/s     1.32 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 152721, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/czech.utf8.txt
   3.025 GB/s (1.1 %)    2.849 Gc/s     1.06 byte/char 
convert_utf8_to_utf16+icelake, input size: 152721, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/czech.utf8.txt
   3.931 GB/s (0.8 %)    3.702 Gc/s     1.06 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 390368, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/english.utf8.txt
  13.120 GB/s (2.5 %)   13.024 Gc/s     1.01 byte/char 
convert_utf8_to_utf16+icelake, input size: 390368, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/english.utf8.txt
  13.816 GB/s (2.6 %)   13.715 Gc/s     1.01 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 86963, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/esperanto.utf8.txt
   5.326 GB/s (1.6 %)    5.152 Gc/s     1.03 byte/char 
convert_utf8_to_utf16+icelake, input size: 86963, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/esperanto.utf8.txt
   5.956 GB/s (1.0 %)    5.762 Gc/s     1.03 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 446908, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/french.utf8.txt
   2.893 GB/s (2.7 %)    2.815 Gc/s     1.03 byte/char 
convert_utf8_to_utf16+icelake, input size: 446908, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/french.utf8.txt
   4.434 GB/s (1.2 %)    4.315 Gc/s     1.03 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 205779, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/german.utf8.txt
   5.485 GB/s (1.2 %)    5.364 Gc/s     1.02 byte/char 
convert_utf8_to_utf16+icelake, input size: 205779, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/german.utf8.txt
   6.085 GB/s (1.0 %)    5.950 Gc/s     1.02 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 181348, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/greek.utf8.txt
   3.402 GB/s (1.0 %)    2.682 Gc/s     1.27 byte/char 
convert_utf8_to_utf16+icelake, input size: 181348, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/greek.utf8.txt
   4.132 GB/s (2.1 %)    3.258 Gc/s     1.27 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 190114, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/hebrew.utf8.txt
   2.896 GB/s (1.1 %)    2.229 Gc/s     1.30 byte/char 
convert_utf8_to_utf16+icelake, input size: 190114, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/hebrew.utf8.txt
   3.658 GB/s (1.1 %)    2.816 Gc/s     1.30 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 396593, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/hindi.utf8.txt
   2.559 GB/s (5.2 %)    1.768 Gc/s     1.45 byte/char 
convert_utf8_to_utf16+icelake, input size: 396593, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/hindi.utf8.txt
   4.713 GB/s (1.1 %)    3.256 Gc/s     1.45 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 164355, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/japanese.utf8.txt
   3.316 GB/s (1.6 %)    2.399 Gc/s     1.38 byte/char 
convert_utf8_to_utf16+icelake, input size: 164355, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/japanese.utf8.txt
   4.136 GB/s (0.8 %)    2.992 Gc/s     1.38 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 97859, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/korean.utf8.txt
   2.753 GB/s (2.4 %)    2.051 Gc/s     1.34 byte/char 
convert_utf8_to_utf16+icelake, input size: 97859, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/korean.utf8.txt
   3.979 GB/s (0.8 %)    2.965 Gc/s     1.34 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 156209, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/persan.utf8.txt
   3.135 GB/s (1.0 %)    2.502 Gc/s     1.25 byte/char 
convert_utf8_to_utf16+icelake, input size: 156209, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/persan.utf8.txt
   3.971 GB/s (0.8 %)    3.170 Gc/s     1.25 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 280660, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/portuguese.utf8.txt
   3.791 GB/s (2.1 %)    3.696 Gc/s     1.03 byte/char 
convert_utf8_to_utf16+icelake, input size: 280660, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/portuguese.utf8.txt
   4.739 GB/s (1.7 %)    4.620 Gc/s     1.03 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 407095, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/russian.utf8.txt
   2.785 GB/s (2.2 %)    2.135 Gc/s     1.30 byte/char 
convert_utf8_to_utf16+icelake, input size: 407095, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/russian.utf8.txt
   3.821 GB/s (1.3 %)    2.929 Gc/s     1.30 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 593589, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/thai.utf8.txt
   2.906 GB/s (3.3 %)    1.981 Gc/s     1.47 byte/char 
convert_utf8_to_utf16+icelake, input size: 593589, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/thai.utf8.txt
   4.790 GB/s (1.5 %)    3.266 Gc/s     1.47 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 195078, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/turkish.utf8.txt
   3.543 GB/s (1.0 %)    3.368 Gc/s     1.05 byte/char 
convert_utf8_to_utf16+icelake, input size: 195078, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/turkish.utf8.txt
   4.663 GB/s (0.9 %)    4.433 Gc/s     1.05 byte/char 
We define the number of bytes to be the number of *input* bytes.
We define a 'char' to be a code point (between 1 and 4 bytes).
===========================
Using ICU version 70.1
testcases: 1
input detected as UTF8
current system detected as icelake
===========================
convert_utf8_to_utf16+haswell, input size: 319029, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/vietnamese.utf8.txt
   1.680 GB/s (3.1 %)    1.487 Gc/s     1.13 byte/char 
convert_utf8_to_utf16+icelake, input size: 319029, iterations: 10000, dataset: unicode_lipsum/wikipedia_mars/vietnamese.utf8.txt
   3.882 GB/s (0.9 %)    3.437 Gc/s     1.13 byte/char 
```

**Comment by lemire** [comment]
Some of the icelake kernel is 'buggy'. I will soon patch it up.

**Comment by lemire** [comment]
The silly icelake bug was fixed. (Resulting code is suboptimal.)

**Comment by lemire** [comment]
Closing. This temporary PR is no longer needed. We will soon complete the library with the new/extended API.

**Pull request closed without merging**
