### PR TITLE
AVX512 feature branch

### PR DESCRIPTION
**Pull request by WojciechMula**
This is a feature branch for AVX512 implementations. (Do not merge until we're done).

Please take a look at the README, there are more details.

Some WIP stuff is already in https://github.com/WojciechMula/toys/tree/master/avx512-utf8-to-utf32, and was preliminary tested with `simdutf` code, but we need proper integration.

MVP:
- [ ] AVX512BW validating UTF8->UTF16
- [ ] AVX512BW non-validating UTF8->UTF16
- [ ] AVX512VBMI validating UTF16->UTF8
- [ ] AVX512VBMI non-validating UTF16->UTF8
- [ ] fallback to Haswell implementation for others

Lower priority:
- [ ] AVX512BW validate UTF-8
- [ ] AVX512BW validate UTF-16
- [ ] AVX512BW count UTF-8
- [ ] AVX512BW count UTF-16
- [ ] AVX512VBMI validate UTF-8
- [ ] AVX512VBMI validate UTF-16
- [ ] AVX512VBMI count UTF-8
- [ ] AVX512VBMI count UTF-16
- [ ] Any boost from AVX512VBMI2? AVX512BITALG?

### CODE REVIEW

**Comment by WojciechMula** [comment]
@lemire Please take a look and share your thoughts.

**Comment by lemire** [comment]
Fantastic. On my todo. Current ETA is next week.

**Comment by WojciechMula** [comment]
> Fantastic. On my todo. Current ETA is next week.

Great. I'll try to complete copying code from my repo. We already have UTF-8 => UTF-16 (both validating and not) for AVX512BW and AVX512VBMI.

**Comment by lemire** [comment]
I am going to merge it to a https://github.com/simdutf/simdutf/ branch to complete it.

**Comment by lemire** [comment]
@clausecker Consider starting from the avx512feature branch from the main simdutf repository.

**Comment by clausecker** [comment]
That is the `avx512feature` branch.

Also, are you done with your fixes for the Muła kernel?  I can start the benchmark set then.

**Comment by lemire** [comment]
The current PR has to do with [WojciechMula:feature-avx512](https://github.com/WojciechMula/simdutf/tree/feature-avx512). It is effectively obsolete.
Yes, you can go to the current avx512feature branch within simdutf. It should build: we have unit tests. If not, I will be happy to investigate!

**Pull request merged**
