### PR TITLE
We check endianness at compile-time.

### PR DESCRIPTION
**Pull request by lemire**
Big endian systems are effectively limited to IBM mainframes in 2022. As a rule, we do not support systems that we do not test. Given that simdutf is not tested on big endian systems, let us warning users of big endian systems. This PR accomplishes that.

Credit to @addaleax for raising the issue. Relates to https://github.com/simdutf/simdutf/issues/204

cc @anonrig

### CODE REVIEW

**Comment by anonrig** [comment]
Please beware that this will inhibit Node.js from updating to the latest version of simdutf.

**Comment by lemire** [comment]
I have updated it so that it is a warning, not a fatal error.

**Review by anonrig — APPROVED** [review]

**Comment by lemire** [comment]
@anonrig It is a testing issue. I am working on trying to get qemu/docker to allow me to setup something kind of CI testing. 

I won't merge this as-is for now.

**Comment by lemire** [comment]
It won't be necessary. Things work fine even under BE. I was being too careful.

**Comment by lemire** [comment]
We still need a patch release.

**Comment by lemire** [comment]
Closing. This will not be merged. We will support big-endian systems by testing through qemu.

**Pull request closed without merging**
