### PR TITLE
Support UTF-16BE

### LINKED ISSUE #3: Add support of UTF-16BE
UTF-16 comes in two flavours (BE, LE). Some of the time, it can be distinguished with a BOM but often we must rely on the platforms' default. There are effectively no big endian platform left (other than legacy systems). I believe that UTF-16LE is effectively the default (e.g., under Windows). 

In time, we may want to support UTF-16BE. It involves a simple byte reversal.

### PR DESCRIPTION
**Pull request by NicolasJiaxin**
Fix #3
Adds support of UTF-16BE by adding all analogous functions that we have for UTF-16LE. For example, validate_utf16 now comes in two flavours: validate_utf16le and validate_utf16be. However, the functions that implement the actual algorithms are now template-based on whether the input/output is little endian or big endian. If big endian, we swap the bytes of using a single shuffle when we load/store data. I also added a function to swap endianness called change_endianness_utf16.

### CODE REVIEW

**Comment by NicolasJiaxin** [comment]
I have not tested the new functions yet. I am also unsure of what change_endianness_utf16 should return. Could it just be a void function? For now, it returns something silly.

**Comment by lemire** [comment]
> I am also unsure of what change_endianness_utf16 should return. Could it just be a void function? 

Definitively. I think it should return `void`.

**Comment by lemire** [comment]
@NicolasJiaxin This code looks very good to me. I just think that we ought to test it (at least minimally).

**Comment by lemire** [comment]
> I added all tests and I did have a few bugs. But it is all working now, except that the debug tests on Visual Studio are getting stuck and I don't know why.

Let me investigate.

**Comment by lemire** [comment]
@NicolasJiaxin When you do (for example)

```
    std::vector<char16_t> utf16be;
    utf16be.reserve(size);
    implementation.change_endianness_utf16(utf16le, size, utf16be.data());
```

You will have that `utf16be.size()` is zero. Your code is technically unsafe. The `reserve` call is just an optimization hint, it may not allocate the memory the way you think (though it will in practice).

So you want to go through and do the following...

```
    std::vector<char16_t> utf16be(size);
    implementation.change_endianness_utf16(utf16le, size, utf16be.data());
```

That should solve the issue. You can also replace `reserve` with `resize`.

Note that your code is 'practically correct' but memory checkers might complain so better fix it.

One problem with using  std::vector is that the input is guaranteed to be zeroed. If you'd want to avoid that... You could also do the following...

```
std::unique_ptr<char16_t[]> utf16be_unique(new char16_t[size]);
char16_t * utf16be = utf16be_unique.get();
implementation.change_endianness_utf16(utf16le, size, utf16be);
```

But I am not sure what the benefit would be.

**Comment by lemire** [comment]
@NicolasJiaxin Try adding some bits of documentation to the README. And then I think we will merge.

**Comment by lemire** [comment]
Great stuff. Merging.

**Pull request merged**
