### PR TITLE
Improve and complement the fuzzing

### PR DESCRIPTION
**Pull request by pauldreik**
This improves the fuzzer build script, and adds a new fuzzer.

# build script improvements
- the build script should be executable
- make it possible to use the build script locally for development
- install the library instead of using the single header, that gives
  error messages report the original source files instead of the
  very high numbers in the amalgamated file
- prepare for having more than one fuzzer file
- explicitly build with C++20

# add a fuzzer for the validation functions
a fuzzer for the validate... functions was added. It is a differential fuzzer, meaning it compares the outcome between different implementations. It catches errors if run on an icelake system, reported here: https://github.com/simdutf/simdutf/issues/432

# add a minimization/cleansing/reproduce script
This makes it easy to convert a crash to a reproducing example. The example is compiled so it is easy to verify the reproducer reproduces.

### CODE REVIEW

**Comment by pauldreik** [comment]
The reason CI-fuzz fails is because the build script is copied during dockerfile build. I submitted https://github.com/google/oss-fuzz/pull/12293 to improve the situation.

**Comment by lemire** [comment]
Great.

**Comment by lemire** [comment]
@pauldreik Please sync with our main branch.

**Comment by pauldreik** [comment]
rebased!

**Comment by lemire** [comment]
@pauldreik It fails with

```
clang++: error: no such file or directory: 'fuzz/roundtrip.cc'
clang++: error: no input files
2024-07-31 21:13:24,472 - root - ERROR - Building fuzzers failed.
2024-07-31 21:13:24,472 - root - ERROR - Error building fuzzers for (commit: 7ae810363de7fccf91ecf8a92b8e4fc306721b6c, pr_ref: refs/pull/437/merge).
```

**Comment by pauldreik** [comment]
> @pauldreik It fails with
> 
> ```
> clang++: error: no such file or directory: 'fuzz/roundtrip.cc'
> clang++: error: no input files
> 2024-07-31 21:13:24,472 - root - ERROR - Building fuzzers failed.
> 2024-07-31 21:13:24,472 - root - ERROR - Error building fuzzers for (commit: 7ae810363de7fccf91ecf8a92b8e4fc306721b6c, pr_ref: refs/pull/437/merge).
> ```

Yes, that will sort itself out either when oss-fuzz merges the PR I linked to above, or this particular PR is merged. It is due to the build script being taken from the main branch rather than the branch to be merged.

**Comment by lemire** [comment]
Merging.

**Pull request merged**
