### PR TITLE
[WIP]UTF-32 validation

### LINKED ISSUE #113: UTF-32 validator
We should have a function to validate UTF-32 inputs.

cc @NicolasJiaxin

### PR DESCRIPTION
**Pull request by NicolasJiaxin**
Fixes #113

### CODE REVIEW

**Comment by NicolasJiaxin** [comment]
@lemire Your suggestion worked and I found it pretty neat! I have added UTF-32 validation with tests.  I am working on benchmarking right now. The workflows are getting stuck on my tests though...

**Comment by NicolasJiaxin** [comment]
Actually, I am not sure how to generate UTF-32 encoded files for benchmarking.

**Comment by lemire** [comment]
@NicolasJiaxin I have update the test repository so that it includes UTF-32 files.

https://github.com/lemire/unicode_lipsum

**Comment by NicolasJiaxin** [comment]
Thanks! I am coming back with numbers.

**Comment by lemire** [comment]
The tests fail because they take too long...

**Comment by lemire** [comment]
Why would the tests take over 15 minutes to run?

**Comment by NicolasJiaxin** [comment]
@lemire Is it possible that the UTF-32 text files are BE? The input is declared invalid, even by the fallback and when I manually read the codepoints it seems that is BE.

**Comment by NicolasJiaxin** [comment]
> Why would the tests take over 15 minutes to run?

I guess you already noticed, but it only occurs for the debug build for some installations of Visual Studio. I saw that in the code related to arm, there are some macros for Visual Studio specifically. Could it be an issue like that?

**Comment by lemire** [comment]
> I guess you already noticed, but it only occurs for the debug build for some installations of Visual Studio. I saw that in the code related to arm, there are some macros for Visual Studio specifically. Could it be an issue like that?

I will investigate.

**Comment by lemire** [comment]
Why it would lead Visual Studio to run forever... I do not know. It should abort. But I suspect that it stands there, waiting for user interaction?

**Comment by lemire** [comment]
> Is it possible that the UTF-32 text files are BE? The input is declared invalid, even by the fallback and when I manually read the codepoints it seems that it is BE.

Let me check it out...

**Comment by lemire** [comment]
> Is it possible that the UTF-32 text files are BE? The input is declared invalid, even by the fallback and when I manually read the codepoints it seems that it is BE.

Should be fixed now. Sorry about that.

**Comment by lemire** [comment]
It is somewhat disappointing that UTF-32 is somewhat slower but that is to be expected.

**Comment by NicolasJiaxin** [comment]
> You had me panicking !!!

Sorry hahaha.... I was also finding it weird that it was so slow.

> It is somewhat disappointing that UTF-32 is somewhat slower but that is to be expected.

You can always check my code. Maybe you will spot something...

**Comment by lemire** [comment]
> You can always check my code. Maybe you will spot something...

I did check it. I think it is fine.

We will be able to merge this PR!

**Comment by lemire** [comment]
Sync with our main branch to catch this commit: https://github.com/simdutf/simdutf/commit/24dc56e4c09f607e606d0f69108c61e873acb718

Please consider extending the related function... Something like this ought to work...

```C++
simdutf_warn_unused encoding_type implementation::autodetect_encoding(const char * input, size_t length) const noexcept {
    // If there is a BOM, then we trust it.
    auto bom_encoding = simdutf::BOM::check_bom(input, length);
    if(bom_encoding != encoding_type::unspecified) { return bom_encoding; }
    // UTF8 is common, it includes ASCII, and is commonly represented
    // without a BOM, so if it fits, go with that. Note that it is still
    // possible to get it wrong, we are only 'guessing'. If some has UTF-16
    // data without a BOM, it could pass as UTF-8.
    //
    // An interesting twist might be to check for UTF-16 ASCII first (every
    // other byte is zero).
    if(validate_utf8(input, length)) { return encoding_type::UTF8; }
    // The next most common encoding that might appear without BOM is probably
    // UTF-16LE, so try that next.
    if((length % 2) == 0) {
      if(validate_utf16(reinterpret_cast<const char16_t*>(input), length/2)) { return encoding_type::UTF16_LE; }
    }
    if((length % 4) == 0) {
      if(validate_utf32(reinterpret_cast<const char32_t*>(input), length/4)) { return encoding_type::UTF32_LE; }
    }
    return encoding_type::unspecified;
}
```

**Pull request merged**
