### PR TITLE
Returning a struct indicating success and length

### LINKED ISSUE #30: Validating and transcoding conversion functions may return a struct indicating length and success
Currently validating conversion functions return a length. This might be better:

```C++
struct result {
  bool is_ok;
  size_t length;
}
```
with structured binding, you can do... `auto [is_ok, length] = convert()`.

### PR DESCRIPTION
**Pull request by NicolasJiaxin**
Fix #30 
I implemented a simple struct result as suggested in #30.

### CODE REVIEW

**Comment by NicolasJiaxin** [comment]
So, I have added a first version for UTF-8 validation. The high-level function is `validate_utf8_with_errors`. It is similar to the regular `validate_utf8` except that it will stop when it detects an error and return a result struct with an error code and the position of the error: 
```c++
struct result {
  error_code error;
  size_t position;
};
```
We have six types of  encoding errors: 
```c++
enum error_code {
  SUCCESS = 0,
  HEADER_BITS,  // Any byte must have fewer than 5 header bits
  TOO_SHORT,    // The leading byte must be followed by N-1 continuation bytes, where N is the UTF-8 character length
                // This is also the error when the input is truncated
  TOO_LONG,     // The leading byte must not be a continuation byte
  OVERLONG,     // The decoded character must be above U+7F for two-byte characters, U+7FF for three-byte characters,
                // and U+FFFF for four-byte characters.
  TOO_LARGE,    // The decoded character must be less than or equal to U+10FFFF
  SURROGATE,    // The decoded character must be not be in U+D800...DFFF (UTF-8 or UTF-32) OR
                // a high surrogate must be followed by a low surrogate and a low surrogate must be preceded by a high surrogate (UTF-16)
  OTHER         // Not related to validation/transcoding
};
```
This should cover all cases for UTF-8, 16 and 32. The OTHER error is for unsupported implementations, but it could be removed.  The position field of the result struct should be the position where the string becomes invalid. For HEADER_BITS, TOO_LARGE and SURROGATE, it is at the position of the troublesome byte itself. For TOO_SHORT, it is at the leading byte of the invalid character (this could arguably be changed at where the missing continuation byte should be). For TOO_LONG, it is at the first extra continuation byte. And for OVERLONG, it is also at the leading byte of the invalid character. In case of success, the position is just the length of the string validated, but this is not very meaningful so it could be changed.

**Comment by lemire** [comment]
The implementation is simpler than what I had in mind, but it is more elegant and probably effectively just as fast.

**Comment by lemire** [comment]
@NicolasJiaxin How fast is it?

**Comment by NicolasJiaxin** [comment]
On haswell, there is a decrease of about 4-5%.
||validate_utf8+haswell (GB/s)| validate_utf8_with_errors+haswell (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf8.txt|12.057|11.605|
|Chinese-Lipsum.utf8.txt|11.882|11.334|
|Emoji-Lipsum.utf8.txt|12.095|11.578|
|Hebrew-Lipsum.utf8.txt|11.853|11.291|
|Hindi-Lipsum.utf8.txt|12.021|11.524|
|Japanese-Lipsum.utf8.txt|12.053|11.514|
|Korean-Lipsum.utf8.txt|12.107|11.569|
|Latin-Lipsum.utf8.txt|57.767|57.729|
|Russian-Lipsum.utf8.txt|12.004|11.504|

**Comment by NicolasJiaxin** [comment]
On westmere, it is way worse.
||validate_utf8+westmere (GB/s)| validate_utf8_with_errors+westmere (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf8.txt|6.011|4.612|
|Chinese-Lipsum.utf8.txt|5.998|4.620|
|Emoji-Lipsum.utf8.txt|5.991|4.619|
|Hebrew-Lipsum.utf8.txt|6.006|4.610|
|Hindi-Lipsum.utf8.txt|6.011|4.609|
|Japanese-Lipsum.utf8.txt|5.999|4.608|
|Korean-Lipsum.utf8.txt|5.997|4.604|
|Latin-Lipsum.utf8.txt|57.462|38.812|
|Russian-Lipsum.utf8.txt|6.005|4.622|

**Comment by lemire** [comment]
@NicolasJiaxin And ARM?

**Comment by lemire** [comment]
I like the haswell numbers, which suggest that on such platforms, we could productively use your new code with barely a scratch. This is great.

My concern has been ARM where I think we may pay a higher price.

**Comment by NicolasJiaxin** [comment]
Actually, the numbers I get with ARM are not bad.

||validate_utf8+arm64 (GB/s)| validate_utf8_with_errors+arm64 (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf8.txt|6.625|6.392|
|Chinese-Lipsum.utf8.txt|6.568|6.384|
|Emoji-Lipsum.utf8.txt|6.541|6.360|
|Hebrew-Lipsum.utf8.txt|6.536|6.383|
|Hindi-Lipsum.utf8.txt|6.638|6.401|
|Japanese-Lipsum.utf8.txt|6.549|6.396|
|Korean-Lipsum.utf8.txt|6.543|6.379|
|Latin-Lipsum.utf8.txt|43.688|38.830|
|Russian-Lipsum.utf8.txt|6.689|6.414|

**Comment by lemire** [comment]
Great news.

**Comment by lemire** [comment]
That’s an important contribution!

**Comment by lemire** [comment]
I think we would need to document it in our README (and them move on to validating transcoding). But otherwise, this feels like it is ready to merge!

**Comment by lemire** [comment]
@NicolasJiaxin I suggest you document the new functions in the README.

**Comment by NicolasJiaxin** [comment]
I have finished adding validate_utf16le_with_errors and benchmarked it. Here are the numbers,

**Haswell**
||validate_utf16+haswell (GB/s)| validate_utf16le_with_errors+haswell (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf16.txt|17.663|17.341|
|Chinese-Lipsum.utf16.txt|17.547|17.225|
|Emoji-Lipsum.utf16.txt|8.413|8.576|
|Hebrew-Lipsum.utf16.txt|16.632|16.405|
|Hindi-Lipsum.utf16.txt|18.787|18.407|
|Japanese-Lipsum.utf16.txt|16.542|16.243|
|Korean-Lipsum.utf16.txt|19.210|18.850|
|Latin-Lipsum.utf16.txt|16.614|16.287|
|Russian-Lipsum.utf16.txt|16.509|16.232|

**Westmere**
||validate_utf16+westmere (GB/s)| validate_utf16le_with_errors+westmere (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf16.txt|15.169|11.598|
|Chinese-Lipsum.utf16.txt|14.590|11.394|
|Emoji-Lipsum.utf16.txt|7.460|7.386|
|Hebrew-Lipsum.utf16.txt|15.409|11.560|
|Hindi-Lipsum.utf16.txt|14.653|11.488|
|Japanese-Lipsum.utf16.txt|14.340|11.347|
|Korean-Lipsum.utf16.txt|14.562|11.424|
|Latin-Lipsum.utf16.txt|14.818|11.614|
|Russian-Lipsum.utf16.txt|15.351|11.650|

**ARM**
||validate_utf16+arm64 (GB/s)| validate_utf16le_with_errors+arm64 (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf16.txt|10.220|10.197|
|Chinese-Lipsum.utf16.txt|10.173|10.125|
|Emoji-Lipsum.utf16.txt|5.358|5.366|
|Hebrew-Lipsum.utf16.txt|10.193|10.162|
|Hindi-Lipsum.utf16.txt|10.198|10.144|
|Japanese-Lipsum.utf16.txt|10.145|10.114|
|Korean-Lipsum.utf16.txt|10.224|10.162|
|Latin-Lipsum.utf16.txt|10.201|10.148|
|Russian-Lipsum.utf16.txt|10.257|10.247|

From what I implemented, we should expect almost not decrease in performance since the UTF-16 validation that we have already stops on errors. This is what we get on haswell and ARM, but again, westmere is badly hit for some reason.

**Comment by lemire** [comment]
> but again, westmere is badly hit for some reason.

Ah.

For the time being, I would not be concerned but it could be that it is fixable.

**Comment by lemire** [comment]
This is good!!!

**Comment by NicolasJiaxin** [comment]
The numbers for validate_utf32_with_errors:

**Haswell**
||validate_utf32+haswell (GB/s)| validate_utf32_with_errors+haswell (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf32.txt|8.581|4.109|
|Chinese-Lipsum.utf32.txt|9.075|4.177|
|Emoji-Lipsum.utf32.txt|9.008|4.191|
|Hebrew-Lipsum.utf32.txt|9.072|4.164|
|Hindi-Lipsum.utf32.txt|9.129|4.166|
|Japanese-Lipsum.utf32.txt|9.210|4.192|
|Korean-Lipsum.utf32.txt|9.130|4.166|
|Latin-Lipsum.utf32.txt|8.394|4.097|
|Russian-Lipsum.utf32.txt|8.671|4.127|

**Westmere**
||validate_utf32+westmere (GB/s)| validate_utf32_with_errors+westmere (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf32.txt|6.447|3.012|
|Chinese-Lipsum.utf32.txt|6.508|3.020|
|Emoji-Lipsum.utf32.txt|6.451|2.848|
|Hebrew-Lipsum.utf32.txt|6.446|2.996|
|Hindi-Lipsum.utf32.txt|6.461|3.018|
|Japanese-Lipsum.utf32.txt|6.482|3.012|
|Korean-Lipsum.utf32.txt|6.517|3.035|
|Latin-Lipsum.utf32.txt|6.368|2.986|
|Russian-Lipsum.utf32.txt|6.412|3.002|

**ARM**
||validate_utf32+arm64 (GB/s)| validate_utf32_with_errors+arm64 (GB/s)|
|-|-|-|
|Arabic-Lipsum.utf32.txt|2.594|2.492|
|Chinese-Lipsum.utf32.txt|2.589|2.484|
|Emoji-Lipsum.utf32.txt|2.587|2.563|
|Hebrew-Lipsum.utf32.txt|2.592|2.491|
|Hindi-Lipsum.utf32.txt|2.592|2.489|
|Japanese-Lipsum.utf32.txt|2.588|2.483|
|Korean-Lipsum.utf32.txt|2.590|2.487|
|Latin-Lipsum.utf32.txt|2.597|2.496|
|Russian-Lipsum.utf32.txt|2.595|2.494|

Haswell and westmere both decreased by more than 50%, but this is probably because the regular UTF-32 validation is an unconditional loop with 3 instructions per loop (+ load instruction) while the validation with error specification has 6 additional instructions and two branches. Surprisingly though, ARM is not affected very much by this.

**Comment by lemire** [comment]
> ARM is not affected very much by this.

ARM is also much slower to begin with.

**Comment by NicolasJiaxin** [comment]
I am moving on to transcoding functions. There are 12 validating transcoding functions, but it should not be too hard to do.

**Comment by NicolasJiaxin** [comment]
So, in the case of transcoding functions, we probably want to return a result and the number of output words written (like we currently have). I have two ideas to do this. The first one is simply to return a std::pair<size_t, result> with both relevant information. The second one is to return a result but with a double meaning for its `position` field (could rename it to something else). In case of a success, the field indicates the number of words written and in case of a failure, it indicates the position of the error. Of course, this would be specify in the documentation and the code, but is it confusing? What do you think @lemire?

**Comment by NicolasJiaxin** [comment]
Anyway, the `position` field is not very meaningful in case of success. Currently, what I did is to set it to the length given by the user for validating functions. But for transcoding functions, we could use it to give additional information such as the number of words written.

**Comment by NicolasJiaxin** [comment]
All validating and transcoding functions have been implemented. I will now start to benchmark all of them to compare them with the original functions.

**Comment by lemire** [comment]
> All validating and transcoding functions have been implemented. I will now start to benchmark all of them to compare them with the original functions.

Wow. This is massive...

**Comment by clausecker** [comment]
Good work!

**Comment by NicolasJiaxin** [comment]
The benchmark comparison on the lipsum file for all functions are [here](https://gist.github.com/NicolasJiaxin/b2102419bcf8805ad76ead0035d377d5).

**Comment by lemire** [comment]
@NicolasJiaxin Do you recommend merging?

**Comment by NicolasJiaxin** [comment]
I think this PR could be very useful. I would recommend however to keep our functions that returns `size_t` as the performance is decreased in some cases. Unless you have some revisions or some comments, I think this is ready to merge!

**Comment by lemire** [comment]
Merging.

**Pull request merged**
